carpets/urls.py
from django.conf.urls import patterns,  url
from django.contrib.auth.decorators import login_required
from carpets.views import (replace_colors, recolor_carpet,
                           room_preview, palette_create_ajax_view, download_pcx,
                           CategoryListView, PaletteListView, PaletteDeleteView, tune_room,
                           search)
from views import logout_ajax

urlpatterns = patterns('',
    url(r'^categories/$', CategoryListView.as_view(), name='categories'),
    url(r'^palettes/$', login_required(PaletteListView.as_view(), login_url='/'), name='palettes'),
    url(r'^recolor_carpet/(?P<item_code>.*)/$', recolor_carpet, name='recolor_carpet'),
    url(r'^replace_colors/(?P<item_code>.*)/(?P<room_id>.*)/$', room_preview, name='room_preview'),
    url(r'^replace_colors/(?P<item_code>.*)/$', replace_colors, name='replace_colors'),
    url(r'^save_palette', palette_create_ajax_view, name='save_palette'),
    url(r'^download_pcx/(?P<pk>\d+)/$', download_pcx, name='download_pcx'),
    url(r'^tune_room/(?P<room_id>.*)/$', tune_room, name='tune_room'),
    # url(r'^room_preview/(?P<pk>\d+)/$', room_preview, name='room_preview'),
    url(r'^palette/(?P<pk>\d+)/delete/$', login_required(PaletteDeleteView.as_view(), login_url='/'), name='delete_palette'),
    url(r'^accounts/logout/$', logout_ajax, name='logout'),
    url(r'^search/', search, name='search'),
    url(r'^(?P<url>.+)$', CategoryListView.as_view(), name='category_details'),
)

carpets/models.py
import tempfile
from django.core.exceptions import ValidationError
from django.core.files.base import File
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings

from PIL import Image
from wand.image import Image as WandImage
from sorl.thumbnail import get_thumbnail
import numpy as np
from jsonfield import JSONField
import json
from utils.rotate import get_rotated


def validate_image(instance):
    try:
        Image.open(instance).getcolors()
    except IOError:
        raise ValidationError(
            message='Unsupported or broken file.',
            code='image_error',
            params=()
        )


class Category(models.Model):
    name = models.CharField(max_length=100, blank=False)
    active = models.BooleanField(default=True)
    description = models.TextField(max_length=300, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey('self', null=True, blank=True,
                               limit_choices_to={'parent__isnull': True})
    cover = models.ImageField(upload_to='category_cover')
    url = models.CharField(max_length=255, unique=True)
    meta = models.TextField(null=True, blank=True,
                            help_text='Example: <br>'
                                      '&lt;meta name="keywords" content="..." /&gt; <br>'
                                      '&lt;meta name="description" content="..." /&gt;')

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __unicode__(self):
        return self.name

    def is_parent(self):
        return self.category_set.exists()


class Carpet(models.Model):
    category = models.ManyToManyField(Category,
                                      related_name="category_carpets", )
    name = models.CharField(blank=False, max_length=100)
    item_code = models.CharField(max_length=30, unique=True)
    image = models.ImageField(upload_to='carpet/images')
    active = models.BooleanField(default=True)
    description = models.TextField(max_length=300, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    def get_thumbnail(self, geometry='600'):
        return get_thumbnail(self.image, geometry, format='PNG', quality=100)

    def preview(self):
        try:
            url = self.get_thumbnail('100').url
        except Exception:
            url = 'https://placeholdit.imgix.net/~text?txtsize=20&txt=No+image+or+corrupted+image&w=100&h=100&txttrack=0'
        return u"<img src='{}'>".format(url)


    preview.allow_tags = True

    def save(self, *args, **kwargs):
        image = self.image
        if image:
            original = WandImage(file=image.file)
            converted = original.convert('pcx')
            tmp_file = tempfile.NamedTemporaryFile()
            converted.save(file=tmp_file)
            self.image = File(tmp_file, image.name)
        super(Carpet, self).save(*args, **kwargs)

    def color_list(self):
        return Image.open(self.image).convert('RGB').getcolors() or []

    def hex_color_list(self):
        return ['%02x%02x%02x' % color[1] for color in self.color_list()]

    def get_colors(self):
        res = []
        color_list = self.hex_color_list()
        color_names = dict(Color.objects.filter(hex__in=color_list).values_list('hex', 'name'))
        for i, color in enumerate(color_list):
            res.append({'name': color_names.get(color, i+1),
                        'hex': color})
        return res

    def __unicode__(self):
        return str(self.name)

    def replace_color(self, im, input_color, output_color):
        if input_color == output_color:
            return im
        data = np.array(im)  # "data" is a height x width x 4 numpy array
        red, green, blue, alpha = data.T  # Temporarily unpack the bands for readability
        # Replace white with red... (leaves alpha values alone...)
        white_areas = (red == input_color[0]) & (green == input_color[1]) & (
            blue == input_color[2])
        data[..., :-1][white_areas.T] = output_color  # Transpose back needed
        return Image.fromarray(data)

    def replace_colors(self, from_colors=None, to_colors=None):
        from_colors = from_colors or []
        to_colors = to_colors or []
        im = Image.open(self.image).convert('RGBA')
        for from_color, to_color in zip(from_colors, to_colors):
            from_color = self.hex_to_rgb(from_color)
            to_color = self.hex_to_rgb(to_color)
            im = self.replace_color(im, from_color, to_color)
        return im

    def get_replace_url(self):
        return reverse('replace_colors', args=[self.item_code])

    def hex_to_rgb(self, colorstring):
        """ convert a hex color string  to an RGB array """
        colorstring = colorstring.strip()
        r, g, b = colorstring[:2], colorstring[2:4], colorstring[4:]
        return [int(val, 16) for val in [r, g, b]]

    def get_url(self):
        return reverse('recolor_carpet', args=[self.item_code])


class Room(models.Model):
    name = models.CharField(blank=False, max_length=50)
    room_code = models.CharField(max_length=50, blank=False)
    image = models.ImageField(upload_to='rooms/images')
    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    scale = models.FloatField(default=1.6)
    repeat = models.FloatField(default=4.0)
    rotate_x = models.FloatField('Perspective', default=70)
    rotate_y = models.FloatField('Horizon', default=50)
    rotate_z = models.FloatField('Orientation', default=0)
    top_offset = models.FloatField(default=0)
    left_offset = models.FloatField(default=0)
    categories = models.ManyToManyField('Category')

    def get_carpet_preview(self, image, scale=None,
                           repeat=None, left_offset=None, top_offset=None,
                           rotate_x=None, rotate_y=None, rotate_z=None):
        room_image = Image.open(self.image)
        room_image.thumbnail([500, 500],
                        Image.ANTIALIAS)
        scale = scale if scale is not None else self.scale
        repeat = repeat if repeat is not None else self.repeat
        left = left_offset if left_offset is not None else self.left_offset
        top = top_offset if top_offset is not None else self.top_offset
        angle_x = rotate_x if rotate_x is not None else self.rotate_x
        angle_y = rotate_y if rotate_y is not None else self.rotate_y
        angle_z = rotate_z if rotate_z is not None else self.rotate_z
        size = room_image.size
        left = left / 100.0
        top = top / 100.0
        image = image.resize([int(size[0] * scale),
                        int(size[0] * scale)],
                        Image.ANTIALIAS)
        image = get_rotated(image, angle_x, angle_y, angle_z, repeat)
        res = Image.new("RGBA", room_image.size)
        offset_left = (res.size[0] - image.size[0]) / 2 + res.size[0] * left
        offset_top = (res.size[1] - image.size[1]) / 2 + res.size[1] * top
        res.paste(image, (int(offset_left), int(offset_top)))
        # res.show()
        res.paste(room_image, (0, 0), room_image)
        return res


    def __unicode__(self):
        return self.name


class Palette(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    data = JSONField(default={})
    carpet = models.ForeignKey(Carpet)
    image = models.ImageField(upload_to='palette/images')

    def get_thumbnail(self, geometry='600'):
        return get_thumbnail(self.image, geometry, format='PNG', quality=100)

    def preview(self):
        try:
            return u"<img src='{}'>".format(self.get_thumbnail('100').url)
        except:
            return "error"
    preview.allow_tags = True

    def carpet_code(self):
        return self.carpet.item_code

    def download(self):
        url = reverse('download_pcx', args=[self.id])
        return u'<a href="{}">download</a>'.format(url)
    download.allow_tags = True

    def get_url(self):
        url = reverse('recolor_carpet', args=[self.carpet.item_code])
        return url + "?hash={}".format(json.dumps(self.data))

    def user_email(self):
        if self.user:
            return self.user.email


class ColorGroup(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True, blank=True)
    order = models.IntegerField(unique=True)

    class Meta:
        ordering = ['order']

    def __unicode__(self):
        return u'{}'.format(self.name)


class Color(models.Model):
    group = models.ForeignKey(ColorGroup)
    name = models.CharField(max_length=255)
    hex = models.CharField(max_length=255)

    def __unicode__(self):
        return u'{} {}'.format(self.group, self.name)

    def color_preview(self):
        return '<span style="color: #{0}">&#9608;&#9608;&#9608;&#9608;&#9608;</span> {0}'.format(self.hex)
    color_preview.allow_tags = True

carpets/templates/carpets/category_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}

<div class="container">

    <div class="col-sm-3 categories">
        <h3>Browse <br> CATEGORIES</h3>
        <hr>

        <div class="list-group">
            {% for category in categories %}
            <ul>
              <li>
              <a href="{% url 'category_details' category.id %}">{{ category.name }}</a>
            </li>
            </ul>
            {% endfor %}
        </div>
    </div>


    <div class="col-sm-8">
        {% if is_paginated %}
            <span class="page-links">
                {% if page_obj.has_previous %}
                  <a href="{% url 'categories'  %}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
              <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
              {% if page_obj.has_next %}
                <a href="{% url 'categories' %}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
            </span>
        {% endif %}
    </div>

    <div class="row">
        <div id="small-img"
             class="col-xs-12 col-sm-12 col-md-12 col-lg-12 center">
            {% for carpet in carpet_list %}
            <ul>
                <li>
                    {% thumbnail carpet.image '250x250' as im %}
                    <img class="img-responsive"
                         style="display: inline-block; width:250px;height:250px"
                         src="{{ im.url }}">
                    {% endthumbnail %}
                    <br>
                    {{ carpet.item_code }}
                    <br>
                    {{ carpet.name }}

                    <div class="list-group">

                        <button><a class="btn"
                                   href="{% url 'recolor_carpet' carpet.item_code %}">VIEW DETAILS</a>
                        </button>
                    </div>
                </li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

carpets/templates/carpets/logout.html
{% load i18n %}

<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
            aria-label="Close"><span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="authModalLabel">{% trans 'Sign Out' %}</h4>
  </div>
  <div class="modal-body">
    {% trans 'Are you sure you want to sign out?' %}
    <form class="login" method="POST" action="{% url 'logout' %}">
      {% csrf_token %}
      {% if redirect_field_value %}
        <input type="hidden" name="{{ redirect_field_name }}"
               value="{{ redirect_field_value }}"/>
      {% endif %}
    </form>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">
      Close
    </button>
    <button id="submitModal" type="submit" data-action="logout" class="btn btn-primary">{% trans "Sign Out" %}</button>
  </div>
</div>

carpets/templates/carpets/palette_confirm_delete.html
<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Delete Pattern</h4>
  </div>
    <div class="container">
  <div class="modal-body">
      <form action="{% url 'delete_palette' palette.id %}" method="post">
        <p>Are you sure you want to delete palette "{{ palette.id }}"?</p>
      </form>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <button type="submit" class="btn btn-danger" id="modal_btn_delete">Confirm</button>
  </div>
</div>

carpets/templates/carpets/palette_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load static from staticfiles %}


{% block extra_js %}
<script src="{% static 'js/jQuery.print.js' %}"></script>
<script src="{% static 'js/palette_list.js' %}"></script>
{% endblock %}
{% block content %}

  <div class="container">
    <div class="scrubs">
        My Account > My Saved Palettes
    </div>

  <hr>

    <div class="carpet_paginator">
      {% if page_obj.has_previous %}
          <a href="?page=1">«</a>
          <a href="?page={{ page_obj.previous_page_number }}">‹</a>
      {% else %}
          <a class="disabled">«</a>
          <a class="disabled">‹</a>
      {% endif %}
      {% for page in paginator.page_range %}
          {% if page == page_obj.number %}
              <a class='selected'>{{ page }}</a>
          {% else %}
              <a href='?page={{ page }}'>{{ page }}</a>
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">›</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">»</a>
      {% else %}
          <a class="disabled">›</a>
          <a class="disabled">»</a>
      {% endif %}
  </div>


    {% for palette in palette_list %}
    <div class="row">
      <ul>
        <li>
          <div class="col-sm-2">
            {% thumbnail palette.image '250x250' as im %}
            <a href="{{ palette.get_url }}">
              <img class="img-responsive"
                   style="display: inline-block; width:163px;height:163px"
                   src="{{ im.url }}">
            </a>
            {% endthumbnail %}
            <a href="{{ palette.image.url }}" class="btn-black-palette download_btn"
               role="button" download>DOWNLOAD</a>
          </div>
          <div class="col-sm-3">
            <button class="btn-black-palette" id="btnPrint" data-image-url='{{ palette.image.url }}'>Print!</button>
          </div>
          <div class="col-sm-2">
            {{ palette.carpet }}
          </div>
          <div class="col-sm-2">
            {{ palette.carpet.category.first }}
          </div>
          <div class="col-sm-3">
            <a data-toggle="modal" data-target="#deleteModal" class="btn-black-palette delete_btn"
               href="{% url 'delete_palette' palette.id %}">Delete Palette № {{ palette.id }}</a>
          </div>
        </li>
      </ul>
    </div>
    <hr>
    {% endfor %}

  </div>

<!-- Modal -->

<div id="deleteModal" class="modal fade" role="dialog">
  <div class="modal-dialog"></div>
</div>

{% endblock content %}

carpets/templates/carpets/recolor_carpet.html
{% extends 'base.html' %}
{% load carpets_utils thumbnail %}
{% load static from staticfiles %}

{% block extra_js %}
  <script src="{% static 'js/jquery.cookie.js' %}"></script>
  <script src="{% static 'js/ajax_csrf.js' %}"></script>
  <script src="{% static 'js/recolor_carpet.js' %}"></script>
{% endblock %}


{% block content %}

  <div class="col-sm-10" id="message"></div>

  <div id="global_div" style="width:1000px;height:650px;margin:0 auto">
    <h4 style="font-family:arial; font-size:20px; color: #5A5A5A; line-height:30px;"></h4>

    <div style="width:800px; height:650px; float: left;">
      <img id="new_img" style="display:none;" src=""/>

      <div id="output_image_zone">
        <div class="text-center loader">
          <br><br><br>
          <img src="{% static 'images/ajax-loader.gif' %}">
        </div>
        <img class="hidden" default-src='{{ carpet.get_replace_url }}'
             id='preview'>
      </div>
    </div>
    <div id="palette_div" style="width:200px; height:560px; float: left;">
      <div id="picker" style="clear:both;"></div>
      <div class="btn-align">
        <div class="button_div" style="width:100%; height:25px;align:center;">
          <label class="buttonstyle_new" id="choose_room">Show In Room
            <input type="button" class="show_in_room" value="room render"
                   style="display:none;">
            </input> </label>
        </div>
        <br/>

        <div class="button_div" style="width:100%; height:25px;align:center;">
          <label class="buttonstyle_new" id="edit_palette"> Show carpet
            <input type="button" id="show_carpet_but" value="Edit Palette"
                   style="display:none;">
            </input> </label>
        </div>
        <br/>

        <div class="button_div" style="width:100%; height:25px;align:center;">
          <label class="buttonstyle_new"> Reset
            <input type="button" id="reset_but" value="Reset"
                   style="display:none;">
            </input> </label>
        </div>
        <br>

          <label class="buttonstyle_new"> Save Changes
            <input id="save" type="button" data-carpet-id="{{ carpet.id }}"
                   data-url="{% url 'save_palette' %}"
                   value="Save Changes"
                   style="display:none;">
            </input>
          </label>

      </div>
      <div id="output_palette"
           style="width:200px; height:300px; margin:20px auto auto auto;clear:both; ">
        {% for color in carpet.get_colors %}
                    <div class="colorbox_wrapper pull-left change_color_item" value="{{ color.hex }}" data-name="{{ color.name }}">
                        <div class="colorbox hand  colorbox_item " style="background-color: #{{ color.hex }}">
                        </div>
                        <span class='color_name'>{{ color.name }}</span>
                    </div>
                {% endfor %}
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal_colorpicker" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title" id="myModalLabel">Select color</h4>
        </div>
        <div class="modal-body">
          <h4 style="clear:both; font-weight:800; margin-top:0px;">
            Instructions: To recolor simply click any color below. To achieve
            the quickest and most cost effective turn-around a running line
            selection is required. To qualify you must choose all the colors in
            your design from a single color group below. </h4>
             {% get_colors as colors %}
                    {% regroup colors by group as colors_groups %}
                    {% for group in colors_groups %}
                        <div class="ui-corner-all"
                             style=" color:#666; padding:6px; height:60px; margin:0px;">
                            <h3 style="clear:both; margin-bottom: 5px; margin-top:0px;">
                                {{ group.grouper }}</h3>
                            {% for color in group.list %}
                                <div class="colorbox_wrapper pull-left">
                                <div class="colorbox hand colorbox_item" style="background-color: #{{ color.hex }}"
                                      value="{{ color.hex }}"
                                      data-name="{{ color.name }}">
                                </div>
                                {{ color.name }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">
            Close
          </button>
          <button type="button" class="btn btn-primary">
            Save changes
          </button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="choose_room_modal" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="clearfix">
            {% for room in rooms %}
              {% thumbnail  room.image '125x125' as im %}
              <div style="float:left; margin-top:15px; margin-left:15px;"><img
                  class="roomchoice_item" value='{{ room.id }}' data-id="6"
                  src="{{ room.image.url }}"
                  height="125" border="0"/>
              </div>
              {% endthumbnail %}
            {% endfor %}
          </div>
          <span style="clear:both;"></span>
        </div>
      </div>
    </div>
  </div>

<div class="modal fade" id="ask_login_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-body">
          <div class="clearfix">
              Login or Signup to be able to view all saved patterns,
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}